# myBatis
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.accountapi
  config-location: classpath:mybatis-config.xml

# DB ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${sql-server-password}
    url: jdbc:mysql://dev.donghyeon.dev:3307/board
    username: root

sql-server-password: ${SQL_PASSWORD}

server:
  port: 8082

