# myBatis
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.accountapi
  config-location: classpath:mybatis-config.xml

# DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${sql-server-password}
    url: jdbc:mysql://board.cjpejm6zlwuk.ap-northeast-2.rds.amazonaws.com:3306/board
    username: admin
# redis 설정
  session:
    storage-type: redis
    timeout: 600
  redis:
    host: localhost
    port: 6379

sql-server-password: ${SQL_PASSWORD}

server:
  port: 8082

